export const DayOfWeek = {
  DAY_OF_WEEK: [
    { id: 0, day: "Thứ 2" },
    { id: 1, day: "Thứ 3" },
    { id: 2, day: "Thứ 4" },
    { id: 3, day: "Thứ 5" },
    { id: 4, day: "Thứ 6" },
    { id: 5, day: "Thứ 7" },
    { id: 6, day: "Chủ Nhật" },
  ],
  LIST_SLOT_EMPTY: [
    {
      time: "06:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "07:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "07:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "08:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "08:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "09:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "09:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "10:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "10:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "11:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "11:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "12:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "12:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "13:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "13:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "14:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "14:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "15:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "15:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "16:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "16:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "17:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "17:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "18:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "18:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "19:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "19:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "20:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "20:30",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
    {
      time: "21:00",
      isSelected1: "not yet",
      message1: "",
      isSelected2: "not yet",
      message2: "",
      isSelected3: "not yet",
      message3: "",
      isSelected4: "not yet",
      message4: "",
      isSelected5: "not yet",
      message5: "",
      isSelected6: "not yet",
      message6: "",
      isSelected7: "not yet",
      message7: "",
    },
  ],
};
