export const province = {
    PROVINCES: [
        { message: 'An Giang' },
        { message: 'Kon Tum' },
        { message: 'Bà Rịa – Vũng Tàu' },
        { message: 'Lai Châu' },
        { message: 'Bắc Giang' },
        { message: 'Lâm Đồng' },
        { message: 'Bắc Kạn' },
        { message: 'Lạng Sơn' },
        { message: 'Bạc Liêu' },
        { message: 'Lào Cai' },
        { message: 'Bắc Ninh' },
        { message: 'Long An' },
        { message: 'Bến Tre' },
        { message: 'Nam Định' },
        { message: 'Bình Định' },
        { message: 'Nghệ An' },
        { message: 'Bình Dương' },
        { message: 'Ninh Bình' },
        { message: 'Bình Phước' },
        { message: 'Ninh Thuận' },
        { message: 'Bình Thuận' },
        { message: 'Phú Thọ' },
        { message: 'Cà Mau' },
        { message: 'Phú Yên' },
        { message: 'Cần Thơ' },
        { message: 'Quảng Bình' },
        { message: 'Cao Bằng' },
        { message: 'Quảng Nam' },
        { message: 'Đà Nẵng' },
        { message: 'Quảng Ngãi' },
        { message: 'Đắk Lắk' },
        { message: 'Quảng Ninh' },
        { message: 'Đắk Nông' },
        { message: 'Quảng Trị' },
        { message: 'Điện Biên' },
        { message: 'Sóc Trăng' },
        { message: 'Đồng Nai' },
        { message: 'Sơn La' },
        { message: 'Đồng Tháp' },
        { message: 'Tây Ninh' },
        { message: 'Gia Lai' },
        { message: 'Thái Bình' },
        { message: 'Hà Giang' },
        { message: 'Thái Nguyên' },
        { message: 'Hà Nam' },
        { message: 'Thanh Hóa' },
        { message: 'Hà Nội' },
        { message: 'Thừa Thiên Huế' },
        { message: 'Hà Tĩnh' },
        { message: 'Tiền Giang' },
        { message: 'Hải Dương' },
        { message: 'TP Hồ Chí Minh' },
        { message: 'Hải Phòng' },
        { message: 'Trà Vinh' },
        { message: 'Hậu Giang' },
        { message: 'Tuyên Quang' },
        { message: 'Hòa Bình' },
        { message: 'Vĩnh Long' },
        { message: 'Hưng Yên' },
        { message: 'Vĩnh Phúc' },
        { message: 'Khánh Hòa' },
        { message: 'Yên Bái' },
        { message: 'Kiên Giang' }
    ]
};